---
title: ""
author: ''
date: "2022-12-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
source("actualizacion.R", encoding = "utf-8")
ultimo <- max(SERIESE$Fecha[!is.na(SERIESE$`BASE_MONETARIA Variaciones Diarias Factores de Explicación de la Base Monetaria Total`)])
```

### Dólar Soja II

Último valor correspondiente al: `r ultimo`

#### Factores de variación de Base Monetaria

```{r bmfactores, fig.align='center'}
factores_BM("2022-11-28")
```

#### M2 y proxies de Factores de Variación

```{r m2factores, fig.align='center'}
source(paste0(dir_objetos,"dolarsoja_m2.R"), encoding = "utf-8")
m2soja_g
```

#### Vencimientos de LELIQ, NOTALIQ y Pases

LELIQ y NOTALIQ

```{r leliq, fig.align='center'}
source(paste0(dir_objetos,"infopases_g.R"), encoding = "utf-8")
perfil_pas_rem_G
```

Pases
```{r pases}
perfil_pas_rem |> filter(Instrumento=="Pases") |> 
  pivot_wider(names_from = "Ente", values_from = "Monto") |> 
  knitr::kable()
```

